const $=id=>document.getElementById(id);
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(v)||0);
async function init(){const r=await fetch('/api/state');if(!r.ok)throw new Error('Cannot load application state');const s=await r.json();$('ticker').innerHTML=s.tickers.map(t=>'<option value="'+t+'">'+t.replace('_',' ')+' · deterministic</option>').join('');$('ticker').value=s.tickers[0];run();}
async function run(){const button=$('run');button.disabled=true;button.textContent='Running…';try{const response=await fetch('/api/backtest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ticker:$('ticker').value||'ACME_TECH',strategy:$('strategy').value,maxTransactions:Number($('limit').value),transactionFee:Number($('fee').value),cooldownDays:Number($('cooldown').value)})});const data=await response.json();if(!response.ok)throw new Error(data.message||data.error);render(data);}catch(e){$('incident').innerHTML='<b>Request could not be completed</b><span>'+escapeHtml(e.message)+'</span>';}finally{button.disabled=false;button.innerHTML='Run backtest <span>→</span>';}}
function render(data){const rs=data.results||[];const bad=rs.some(r=>r.status!=='valid');$('incident').classList.toggle('healthy',!bad);$('incident').innerHTML=bad?'<b>⚠ Production Analytics Anomaly Detected</b><span>One or more policies returned anomalous results. Reconcile fills, fees, and state transitions.</span>':'<b>✓ Backtesting Engine Healthy</b><span>All selected strategy policies passed validation.</span>';
 $('results').innerHTML=rs.map(r=>'<tr><td>'+escapeHtml(r.strategy)+'</td><td class="money '+(r.profit>=0?'positive':'negative')+'">'+money(r.profit)+'</td><td>'+r.trades+'</td><td class="money">'+money(r.maxDrawdown)+'</td><td class="money">'+money(r.telemetry.feesPaid)+'</td><td>'+r.telemetry.cooldownDaysObserved+'</td><td class="status '+(r.status==='valid'?'ok':'')+'">'+(r.status==='valid'?'✓ Valid Strategy':'⚠ Unexpected')+'</td></tr>').join('');
 const selected=rs[0];$('run-tag').textContent=selected?selected.strategy.toUpperCase():'NO RESULTS';$('telemetry').innerHTML=selected?metric('Days processed',selected.telemetry.daysProcessed)+metric('BUY events',selected.telemetry.buySignals)+metric('SELL events',selected.telemetry.sellSignals)+metric('Completed trades',selected.trades)+metric('Fees paid',money(selected.telemetry.feesPaid))+metric('Cooldown days',selected.telemetry.cooldownDaysObserved)+metric('Peak portfolio',money(selected.telemetry.peakPortfolioValue))+metric('Net profit',money(selected.telemetry.netProfit)):'';
 const tx=selected?.transactions||[];$('transactions').innerHTML=tx.length?tx.map(t=>'<tr><td class="'+(t.action==='BUY'?'positive':'negative')+'">'+t.action+'</td><td>'+t.day+'</td><td>'+money(t.price)+'</td><td>'+money(t.fee)+'</td><td>'+(t.action==='SELL'?money(t.realizedProfit):'—')+'</td></tr>').join(''):'<tr><td colspan="5" class="empty">No completed executions in this run.</td></tr>';
 $('window').textContent=data.prices.length+' sessions · '+data.ticker;$('chart-title').textContent=data.ticker.replace('_',' ')+' · closing price';draw(data.prices,tx);}
function metric(k,v){return '<div class="metric"><span>'+k+'</span><b>'+v+'</b></div>'}
function draw(prices,tx){const el=$('chart');if(!prices?.length){el.innerHTML='';return;}const w=760,h=270,pad={l:48,r:15,t:15,b:27};const min=Math.min(...prices),max=Math.max(...prices),range=max-min||1;const x=i=>pad.l+i*(w-pad.l-pad.r)/Math.max(1,prices.length-1),y=v=>pad.t+(max-v)*(h-pad.t-pad.b)/range;const points=prices.map((v,i)=>x(i)+','+y(v)).join(' ');let grid='';for(let i=0;i<=4;i++){const v=min+range*i/4,yy=y(v);grid+='<line x1="'+pad.l+'" y1="'+yy+'" x2="'+(w-pad.r)+'" y2="'+yy+'" stroke="#25354b" stroke-dasharray="3 5"/><text x="'+(pad.l-8)+'" y="'+(yy+4)+'" fill="#8191a7" text-anchor="end" font-size="10">'+money(v)+'</text>';}const marks=tx.map(t=>{const xx=x(t.day-1),yy=y(t.price),buy=t.action==='BUY',d=buy?'M'+xx+' '+(yy-8)+'l-6 10h12z':'M'+xx+' '+(yy+8)+'l-6-10h12z';return '<path d="'+d+'" fill="'+(buy?'#35d39a':'#f56e7b')+'"><title>'+t.action+' day '+t.day+': '+money(t.price)+'</title></path>';}).join('');let labels='';const step=Math.ceil(prices.length/7);prices.forEach((_,i)=>{if(i%step===0)labels+='<text x="'+x(i)+'" y="'+(h-5)+'" fill="#718096" text-anchor="middle" font-size="9">D'+(i+1)+'</text>';});el.innerHTML='<svg viewBox="0 0 '+w+' '+h+'" role="img" aria-label="Market price history">'+grid+'<polyline points="'+points+'" fill="none" stroke="#71a7ff" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>'+marks+labels+'</svg>';}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
$('run').addEventListener('click',run);$('reset').addEventListener('click',async()=>{await fetch('/api/reset',{method:'POST'});await run();});init().catch(e=>{$('incident').innerHTML='<b>Service unavailable</b><span>'+escapeHtml(e.message)+'</span>';});
